"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Report = { totalFoods: number; totals: { calories: number; protein: number; carbs: number; fat: number }; daily: { label: string; calories: number }[] };
const today = new Date().toISOString().slice(0, 10);

export default function ReportsPage() {
  const router = useRouter(); const [range, setRange] = useState("week"); const [date, setDate] = useState(today); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(""); const [patientId] = useState(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("patientId") || "");
  useEffect(() => { const target = patientId ? `&patientId=${encodeURIComponent(patientId)}` : ""; fetch(`/api/reports?range=${range}&date=${date}${target}`).then(async (response) => { if (response.status === 401) { router.replace("/login"); return; } const data = await response.json(); if (response.ok) { setReport(data); setError(""); } else setError(data.error || "No fue posible cargar el reporte."); }).catch(() => setError("No fue posible cargar el reporte.")); }, [range, date, patientId, router]);
  const max = Math.max(...(report?.daily.map((item) => item.calories) || [1]), 1);
  return <main className="reports-page"><header className="report-header"><div><Link href="/">← Volver al panel</Link><p className="eyebrow">REPORTES</p><h1>Tu consumo en perspectiva.</h1></div><div className="report-actions"><input aria-label="Fecha de reporte" type="date" value={date} onChange={(event) => setDate(event.target.value)} /><button className="print-report" onClick={() => window.print()}>Imprimir reporte</button></div></header><section className="report-tabs"><button className={range === "day" ? "selected" : ""} onClick={() => setRange("day")}>Día</button><button className={range === "week" ? "selected" : ""} onClick={() => setRange("week")}>Semana</button><button className={range === "month" ? "selected" : ""} onClick={() => setRange("month")}>Mes</button></section>{error && <p className="auth-error">{error}</p>}{report && <><section className="report-stats"><article><span>CALORÍAS</span><strong>{report.totals.calories.toLocaleString("es-MX")}</strong><small>kcal consumidas</small></article><article><span>REGISTROS</span><strong>{report.totalFoods}</strong><small>alimentos registrados</small></article><article><span>PROTEÍNA</span><strong>{report.totals.protein}g</strong><small>en este periodo</small></article><article><span>CARBOHIDRATOS</span><strong>{report.totals.carbs}g</strong><small>en este periodo</small></article></section><section className="report-chart"><div><h2>Calorías por día</h2><p>Consulta el comportamiento de tu consumo en el periodo elegido.</p></div><div className="bar-chart">{report.daily.length ? report.daily.map((item) => <div className="bar-item" key={item.label}><b>{item.calories}</b><span style={{ height: `${Math.max((item.calories / max) * 180, 8)}px` }} /><small>{item.label}</small></div>) : <p className="empty-state">Aún no hay registros en este periodo.</p>}</div></section><section className="macro-card"><div><span>PROTEÍNA</span><strong>{report.totals.protein}g</strong></div><div><span>CARBOHIDRATOS</span><strong>{report.totals.carbs}g</strong></div><div><span>GRASA</span><strong>{report.totals.fat}g</strong></div></section></>}</main>;
}
